# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
import res
import icons_rc
class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1220, 670)
                MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setStyleSheet("")
                self.centralwidget.setObjectName("centralwidget")
                # self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(20, 0, 1221, 671))
                # self.label.setStyleSheet()
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(30, 30, 1161, 41))
                self.label_2.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
        "border-radius:15px;\n"
        "border: 1.5px solid white;"
        "QPushButton#btn_details,QPushButton#btn_add_product,QPushButton#btn_delete_product,QPushButton#btn_update_product{\n"
        "         background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98 , 112, 226));\n"
        "        color: rgba(255, 255, 255, 210);\n"
        "        border-radius:5px;\n"
        "}\n"
        "QPushButton#btn_details:pressed,QPushButton#btn_add_product:pressed,QPushButton#btn_delete_product:pressed,QPushButton#btn_update_product:pressed{\n"
        "        padding-left:5px;\n"
        "        padding-top:5px;\n"
        "        background-color:rgba(105, 118, 132, 200);\n"
        "}\n"
        "QPushButton#btn_details:hover,QPushButton#btn_add_product:hover,QPushButton#btn_delete_product:hover,QPushButton#btn_update_product:hover{\n"
        "        background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118 , 132, 226));\n"
        "}\n"
        ""
        )
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.widget = QtWidgets.QWidget(self.centralwidget)
                self.widget.setGeometry(QtCore.QRect(1090, 40, 81, 21))
                self.widget.setStyleSheet("")
                self.widget.setObjectName("widget")
                self.btn_max_3 = QtWidgets.QPushButton(self.widget)
                self.btn_max_3.setGeometry(QtCore.QRect(30, 0, 21, 17))
                self.btn_max_3.setStyleSheet("QPushButton#btn_max_3{\n"
        "         background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0477, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(85, 98 , 112, 226));\n"
        "        color: rgba(255, 255, 255, 210);\n"
        "        border-radius:5px;\n"
        "}\n"
        "QPushButton#btn_max_3:pressed{\n"
        "        padding-left:5px;\n"
        "        padding-top:5px;\n"
        "        background-color:rgba(105, 118, 132, 200);\n"
        "}\n"
        "QPushButton#btn_max_3:hover{\n"
        "        background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118 , 132, 226));\n"
        "}\n"
        "")
                self.btn_max_3.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btn_max_3.setIcon(icon)
                self.btn_max_3.setObjectName("btn_max_3")
                self.btn_max_2 = QtWidgets.QPushButton(self.widget)
                self.btn_max_2.setGeometry(QtCore.QRect(60, 0, 21, 17))
                self.btn_max_2.setStyleSheet("QPushButton#btn_max_2{\n"
        "         background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0477, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(85, 98 , 112, 226));\n"
        "        color: rgba(255, 255, 255, 210);\n"
        "        border-radius:5px;\n"
        "}\n"
        "QPushButton#btn_max_2:pressed{\n"
        "        padding-left:5px;\n"
        "        padding-top:5px;\n"
        "        background-color:rgba(105, 118, 132, 200);\n"
        "}\n"
        "QPushButton#btn_max_2:hover{\n"
        "        background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118 , 132, 226));\n"
        "}\n"
        "")
                self.btn_max_2.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap(":/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btn_max_2.setIcon(icon1)
                self.btn_max_2.setObjectName("btn_max_2")
                
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(10, 10, 1201, 641))
                self.label_3.setStyleSheet("background-image: url(:/image/bg2.jpg);\n"
        "border-radius:15px;\n"
        "")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(30, 80, 1161, 551))
                self.label_4.setStyleSheet("background-color:rgba(0, 0, 0, 150);\n"
        "border-radius:15px;\n"
        "border: 1.5px solid white;")
                self.label_4.setText("")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(480, 40, 261, 21))
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_5.setObjectName("label_5")
                self.btn_add_product = QtWidgets.QPushButton(self.centralwidget)
                self.btn_add_product.setGeometry(QtCore.QRect(640, 560, 161, 51))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.btn_add_product.setFont(font)
                self.btn_add_product.setStyleSheet("background-color:rgba(0, 0, 0, 150);\n"
        "border: 1.5px solid white;\n"
        "color:white")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap(":/icons/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btn_add_product.setIcon(icon3)
                self.btn_add_product.setIconSize(QtCore.QSize(30, 30))
                self.btn_add_product.setObjectName("btn_add_product")
                self.btn_delete_product = QtWidgets.QPushButton(self.centralwidget)
                self.btn_delete_product.setGeometry(QtCore.QRect(1000, 560, 161, 51))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.btn_delete_product.setFont(font)
                self.btn_delete_product.setStyleSheet("QPushButton#btn_delete_product:hover{\n"
        "         background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0477, stop:0 rgba(49, 83, 146, 80), stop:1 rgba(85, 98 , 112, 226));\n"
        "        color: rgba(250, 250, 250, 250);\n"
        "        border-radius:5px;\n"
                "}\n"
                "QPushButton#btn_delete_product{\n"
                "background-color:rgba(0, 0, 0, 150);\n"
                "border: 1.5px solid white;\n"
                "color:white"
                "}\n"

                        
        )
                icon4 = QtGui.QIcon()
                icon4.addPixmap(QtGui.QPixmap(":/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btn_delete_product.setIcon(icon4)
                self.btn_delete_product.setIconSize(QtCore.QSize(30, 30))
                self.btn_delete_product.setObjectName("btn_delete_product")
                self.btn_update_product = QtWidgets.QPushButton(self.centralwidget)
                self.btn_update_product.setGeometry(QtCore.QRect(820, 560, 161, 51))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.btn_update_product.setFont(font)
                self.btn_update_product.setStyleSheet("background-color:rgba(0, 0, 0, 150);\n"
        "border: 1.5px solid white;\n"
        "color:white")
                icon5 = QtGui.QIcon()
                icon5.addPixmap(QtGui.QPixmap(":/icons/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btn_update_product.setIcon(icon5)
                self.btn_update_product.setIconSize(QtCore.QSize(30, 30))
                self.btn_update_product.setObjectName("btn_update_product")
                self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
                self.tableWidget.setGeometry(QtCore.QRect(60, 110, 1101, 431))
                self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                self.tableWidget.setAcceptDrops(False)
                self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.tableWidget.setAutoFillBackground(False)
                self.tableWidget.setStyleSheet("QTableWidget\n"
        "{\n"
        "    background-color:rgba(0, 0, 0, 150);\n"
        "    border-radius:15px;\n"
        "    border: 1.5px solid white;\n"
        "    color: white\n"
        "}\n"
        "\n"
        "QHeaderView\n"
        "{\n"
        "    border:none;\n"
        "    background-color: rgba(0, 0, 0, 100);\n"
        "    color: rgb(0, 0, 0);\n"
        "    border:2px solid white;\n"
        "    border-radius:10px;\n"
        "}\n"
        "QHeaderView::section\n"
        "{\n"
        "    border:none;\n"
        "    background-color: rgba(0, 0, 0, 100);\n"
        "    border:2px solid white;\n"
        "    color: rgb(255, 255, 255);\n"
        "    border-radius:10px;\n"
        "}")
                self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
                self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
                self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.tableWidget.setLineWidth(1)
                self.tableWidget.setMidLineWidth(2)
                self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
                self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
                self.tableWidget.setAlternatingRowColors(False)
                self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
                self.tableWidget.setShowGrid(True)
                self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
                self.tableWidget.setObjectName("tableWidget")
                self.tableWidget.setColumnCount(4)
                self.tableWidget.setRowCount(1)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(0, 0, item)
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(0, 1, item)
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(0, 2, item)
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(0, 3, item)
                self.tableWidget.horizontalHeader().setVisible(True)
                self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
                self.tableWidget.horizontalHeader().setDefaultSectionSize(273)
                self.tableWidget.horizontalHeader().setHighlightSections(True)
                self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
                self.tableWidget.horizontalHeader().setStretchLastSection(True)
                self.tableWidget.verticalHeader().setVisible(False)
                self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
                self.tableWidget.verticalHeader().setHighlightSections(False)
                self.tableWidget.verticalHeader().setSortIndicatorShown(False)
                self.btn_details = QtWidgets.QPushButton(self.centralwidget)
                self.btn_details.setGeometry(QtCore.QRect(460, 560, 161, 51))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.btn_details.setFont(font)
                self.btn_details.setStyleSheet("background-color:rgba(0, 0, 0, 150);\n"
        "border: 1.5px solid white;\n"
        "color:white")
                icon6 = QtGui.QIcon()
                icon6.addPixmap(QtGui.QPixmap(":/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btn_details.setIcon(icon6)
                self.btn_details.setIconSize(QtCore.QSize(30, 30))
                self.btn_details.setObjectName("btn_details")
                self.label_3.raise_()
                self.label_4.raise_()
                self.label.raise_()
                self.label_2.raise_()
                self.widget.raise_()
                self.label_5.raise_()
                self.btn_add_product.raise_()
                self.btn_delete_product.raise_()
                self.btn_update_product.raise_()
                self.tableWidget.raise_()
                self.btn_details.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
               
                # Assigning Exit button:
                self.btn_max_2.clicked.connect(lambda:exit())   

                self.btn_max_3.clicked.connect(lambda: MainWindow.showMinimized())

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_5.setText(_translate("MainWindow", "Q R -  S T O C K  M A S T E R"))
                self.btn_add_product.setText(_translate("MainWindow", "Add Product"))
                self.btn_delete_product.setText(_translate("MainWindow", "Delete Product"))
                self.btn_update_product.setText(_translate("MainWindow", "Update Product"))
                self.tableWidget.setSortingEnabled(True)
                item = self.tableWidget.verticalHeaderItem(0)
                item.setText(_translate("MainWindow", "1"))
                item = self.tableWidget.horizontalHeaderItem(0)
                item.setText(_translate("MainWindow", "Product Name"))
                item = self.tableWidget.horizontalHeaderItem(1)
                item.setText(_translate("MainWindow", "Stock"))
                item = self.tableWidget.horizontalHeaderItem(2)
                item.setText(_translate("MainWindow", "Date Created"))
                item = self.tableWidget.horizontalHeaderItem(3)
                item.setText(_translate("MainWindow", "Date Updated"))
                __sortingEnabled = self.tableWidget.isSortingEnabled()
                self.tableWidget.setSortingEnabled(False)
                self.tableWidget.setSortingEnabled(__sortingEnabled)
                self.btn_details.setText(_translate("MainWindow", "Product Details"))

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
